package com.example.util

import com.example.model.AppLanguage

object LanguageManager {

    fun getString(key: String, language: AppLanguage): String {
        val entry = strings[key] ?: return key
        return if (language == AppLanguage.ASSAMESE) entry.second else entry.first
    }

    private val strings = mapOf(
        "app_name" to Pair("Student Education", "ষ্টুডেণ্ট এডুকেশ্বন"),
        "school_name" to Pair("PM Shri Berbhngi HS School", "পি এম শ্ৰী বেৰভাঙী উচ্চতৰ মাধ্যমিক বিদ্যালয়"),
        "welcome" to Pair("Welcome", "স্বাগতম"),
        "home" to Pair("Home", "গৃহ"),
        "courses" to Pair("Courses", "পাঠ্যক্ৰম"),
        "classes" to Pair("Classes", "শ্ৰেণীসমূহ"),
        "exam" to Pair("Exam", "পৰীক্ষা"),
        "profile" to Pair("Profile", "প্ৰফাইল"),
        "continue_learning" to Pair("Continue Learning", "অধ্যয়ন অব্যাহত ৰাখক"),
        "my_courses" to Pair("My Courses", "মোৰ পাঠ্যক্ৰমসমূহ"),
        "todays_classes" to Pair("Today's Classes", "আজিৰ শ্ৰেণীসমূহ"),
        "upcoming_live_class" to Pair("Upcoming Live Class", "অনাগত লাইভ ক্লাছ"),
        "recent_notes" to Pair("Recent Notes", "শেহতীয়া নোটচ্"),
        "upcoming_exams" to Pair("Upcoming Exams", "অনাগত পৰীক্ষাসমূহ"),
        "latest_results" to Pair("Latest Results", "শেহতীয়া ফলাফল"),
        "attendance" to Pair("Attendance", "উপস্থিতি"),
        "my_progress" to Pair("My Progress", "মোৰ অগ্ৰগতি"),
        "notifications" to Pair("Notifications", "অধিসূচনা"),
        "doubt_ask" to Pair("Ask Doubt", "প্ৰশ্ন সোধক"),
        "video_classes" to Pair("Video Classes", "ভিডিঅ' ক্লাছ"),
        "live_classes" to Pair("Live Classes", "লাইভ ক্লাছ"),
        "pdf_notes" to Pair("PDF & Study Notes", "পিডিএফ আৰু নোটচ্"),
        "online_exams" to Pair("Online Exams", "অনলাইন পৰীক্ষা"),
        "results_marks" to Pair("Results & Marks", "ফলাফল আৰু নম্বৰ"),
        "messages" to Pair("Teacher Messages", "শিক্ষক বাৰ্তালাপ"),
        "search_hint" to Pair("Search subjects, videos, notes...", "বিষয়, ভিডিঅ', নোটচ্ সন্ধান কৰক..."),
        "watch_now" to Pair("Watch Now", "এতিয়া চাওক"),
        "join_live" to Pair("Join Live Class", "লাইভ শ্ৰেণীত অংশ লওক"),
        "read_pdf" to Pair("Read Material", "অধ্যয়ন সামগ্ৰী পঢ়ক"),
        "take_test" to Pair("Take Exam", "পৰীক্ষা দিয়ক"),
        "enroll_now" to Pair("Enroll Now - ₹100", "ভৰ্তি হওক - ₹১০০"),
        "purchased" to Pair("Enrolled", "ভৰ্তি হোৱা হৈছে"),
        "present" to Pair("Present", "উপস্থিত"),
        "absent" to Pair("Absent", "অনুপস্থিত"),
        "total_classes" to Pair("Total Classes", "মুঠ শ্ৰেণী"),
        "percentage" to Pair("Percentage", "শতাংশ"),
        "status_pending" to Pair("Pending", "বিচাৰাধীন"),
        "status_answered" to Pair("Answered", "উত্তৰ দিয়া হৈছে"),
        "status_solved" to Pair("Solved", "সমাধান কৰা হ'ল"),
        "login" to Pair("Student Login", "ছাত্ৰ-ছাত্ৰী লগইন"),
        "teacher_login" to Pair("Teacher / Admin Login", "শিক্ষক / প্ৰশাসক লগইন"),
        "register" to Pair("Student Registration", "নতুন ছাত্ৰ-ছাত্ৰী পঞ্জীয়ন"),
        "logout" to Pair("Logout", "প্ৰস্থান কৰক"),
        "switch_language" to Pair("Change Language", "ভাষা সলনি কৰক"),
        "about_school" to Pair("About School", "বিদ্যালয়ৰ বিষয়ে"),
        "about_developer" to Pair("About Developer", "এপ ডেভলপাৰৰ বিষয়ে"),
        "roll_no" to Pair("Roll No", "ৰোল নম্বৰ"),
        "parent_name" to Pair("Parent's Name", "অভিভাৱকৰ নাম"),
        "phone_number" to Pair("Phone Number", "ফোন নম্বৰ"),
        "email_address" to Pair("Email Address", "ইমেইল ঠিকনা"),
        "class_label" to Pair("Class", "শ্ৰেণী"),
        "select_class" to Pair("Select Class", "শ্ৰেণী বাছক"),
        "submit" to Pair("Submit", "দাখিল কৰক"),
        "cancel" to Pair("Cancel", "বাতিল কৰক"),
        "price" to Pair("Price", "মূল্য"),
        "duration" to Pair("Duration", "সময়সীমা"),
        "teacher" to Pair("Teacher", "শিক্ষক"),
        "chapter" to Pair("Chapter", "অধ্যায়"),
        "score" to Pair("Score", "নম্বৰ"),
        "grade" to Pair("Grade", "শ্ৰেণী/গ্ৰেড"),
        "admin_dashboard" to Pair("Admin Dashboard", "প্ৰশাসক পেনেল"),
        "teacher_dashboard" to Pair("Teacher Dashboard", "শিক্ষক পেনেল"),
        "quick_demo" to Pair("Quick Demo Login", "তৎক্ষণাৎ ডেমো লগইন"),
        "pay_upi" to Pair("Pay via UPI (₹100)", "UPI যোগে পৰিশোধ কৰক (₹১০০)"),
        "payment_successful" to Pair("Payment Successful", "পৰিশোধ সফল হ'ল"),
        "subject_assamese" to Pair("Assamese", "অসমীয়া"),
        "subject_english" to Pair("English", "ইংৰাজী"),
        "subject_education" to Pair("Education", "শিক্ষা"),
        "subject_iti" to Pair("ITI", "আই টি আই"),
        "subject_pol_science" to Pair("Political Science", "ৰাজনীতি বিজ্ঞান"),
        "subject_healthcare" to Pair("Healthcare", "স্বাস্থ্যসেৱা"),
        "subject_sociology" to Pair("Sociology", "সমাজতত্ত্ব"),
        "subject_bihu" to Pair("Bihu", "বিহু"),
        "subject_history" to Pair("History", "ইতিহাস"),
        "subject_dance" to Pair("Dance", "নৃত্য")
    )
}
